name: testPython

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu_latest
        steps:
              uses: actions/checkout@v2
