name: testPython

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  buildAndTest:
    runs-on: ubuntu-latest
      steps:
        - name: Check out last commit
          uses: actions/checkout@v2
        - name: Set up Python 3.9
          uses: actions/setup-python@v2
          with:
            python-version: 3.9
        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pytest numpy
        - name: Run Test Scripts
          run: python -m pytest
